require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AdmixerExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-admixer', :path => '../..'
  pod 'react-native-admixer-admob-mediation', :path => '../../../react-native-admixer-admob-mediation'
  pod 'Google-Mobile-Ads-SDK', '9.6.0'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0' })
#  post_install do |installer|
#    flipper_post_install(installer)
#  end

end
